# Generated by Django 5.0.3 on 2024-04-07 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskboarduser',
            name='username',
            field=models.CharField(max_length=24, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Minimum username length is 3 characters.'), django.core.validators.RegexValidator('[A-Za-z0-9_-]', 'Usernames may only have alphanumerical characters, underscores, and dashes.')]),
        ),
    ]
