# Generated by Django 5.0.3 on 2024-06-16 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_taskboarduser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskboarduser',
            name='username',
            field=models.CharField(max_length=24, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Minimum username length is 3 characters.'), django.core.validators.RegexValidator('[a-zA-Z0-9_-]+$', 'Usernames may only have alphanumerical characters, underscores, and dashes.')]),
        ),
    ]
