# Generated by Django 5.0.3 on 2024-06-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_taskboarduser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskboarduser',
            name='about_me',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='taskboarduser',
            name='title',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
    ]
