# Generated by Django 5.0.3 on 2024-08-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_taskboarduser_about_me_taskboarduser_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NTSK', 'New Task'), ('NCMT', 'New Comment'), ('TKSC', 'Task Status Change'), ('UKWN', 'Unknown')], default='UKWN', max_length=4)),
            ],
        ),
    ]
