# Generated by Django 5.0.3 on 2024-08-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
