# Generated by Django 5.0.3 on 2024-03-25 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='No title provided.', max_length=200)),
                ('description', models.CharField(blank=True, default='No description provided.', max_length=1000)),
                ('category', models.CharField(choices=[('NONE', 'None'), ('GAME', 'Games'), ('SITE', 'Websites'), ('APPS', 'Apps'), ('MISC', 'Miscellaneous')], default='NONE', max_length=4)),
                ('type', models.CharField(choices=[('NONE', 'None'), ('CNPT', 'Concept'), ('IDEA', 'Idea'), ('ISSU', 'Issue'), ('UNST', 'Unsorted')], default='NONE', max_length=4)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('NOPE', 'Rejected'), ('STOP', 'Cancelled'), ('WORK', 'In Progress'), ('REVW', 'Reviewing'), ('DONE', 'Complete')], default='TODO', max_length=4)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
