# Generated by Django 5.0.3 on 2024-03-25 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_datecreated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dateCreated',
            new_name='date_created',
        ),
    ]
