# Generated by Django 5.0.3 on 2024-03-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_datecreated_task_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('WORK', 'In Progress'), ('REVW', 'Reviewing'), ('DONE', 'Complete'), ('NOPE', 'Rejected'), ('STOP', 'Cancelled')], default='TODO', max_length=4),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('TASK', 'Task'), ('FEAT', 'Feature'), ('PROJ', 'New Project'), ('ISSU', 'Issue'), ('UNKN', 'UNKNOWN')], default='UNKN', max_length=4),
        ),
    ]
