# Generated by Django 5.0.3 on 2024-04-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_category_alter_task_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='summary',
            field=models.CharField(blank=True, default='No summary provided.', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='No description provided.', max_length=4080),
        ),
    ]
