# Generated by Django 5.0.3 on 2024-04-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_title_task_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='poster',
            new_name='author',
        ),
        migrations.AddField(
            model_name='task',
            name='status_comment',
            field=models.CharField(blank=True, default='Task successfuly created.', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('TASK', 'Task'), ('FEAT', 'Feature'), ('PROJ', 'Project'), ('ISSU', 'Issue'), ('UNKN', 'UNKNOWN')], default='UNKN', max_length=4),
        ),
    ]
