# Generated by Django 5.0.3 on 2024-04-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_project_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=4080),
        ),
        migrations.AlterField(
            model_name='task',
            name='status_comment',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('TASK', 'Task'), ('FEAT', 'Feature'), ('PROJ', 'Project'), ('ISSU', 'Issue')], default='TASK', max_length=4),
        ),
    ]
