# Generated by Django 5.0.3 on 2024-04-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('GAME', 'Game'), ('MSIC', 'Music'), ('SITE', 'Website'), ('APPL', 'Application'), ('OTHR', 'Other')], default='OTHR', max_length=4),
        ),
    ]
