# Generated by Django 5.0.3 on 2024-04-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=4080),
        ),
    ]
