# Generated by Django 5.0.3 on 2024-04-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status_comment',
            new_name='comments',
        ),
    ]
