# Generated by Django 5.0.3 on 2024-04-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('REVW', 'Reviewing'), ('TODO', 'To Do'), ('WORK', 'In Progress'), ('DONE', 'Complete'), ('NOPE', 'Rejected'), ('STOP', 'Cancelled')], default='REVW', max_length=4),
        ),
    ]
