# Generated by Django 5.0.3 on 2024-08-08 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
